apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: profile-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: APP_COLOR
          value: "blue"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: profile-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
      containers:
      - name: profile-container
        image: profile-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: APP_COLOR
          value: "yellow"
        resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      volumeMounts:
      - name: config-volume
        mountPath: /app/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: profile-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
  namespace: prod
spec:
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: profile-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: APP_COLOR
          value: "red"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: profile-pvc
