apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: dev
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: test
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: prod
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
