server:
  port: 8080

spring:
  application:
    name: qr-menu-generator
  
  datasource:
    url: jdbc:h2:file:./data/qrmenugendb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# Application configuration
app:
  base-url: http://localhost:8080
  
# CORS configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:80
    - http://localhost

# CORS configuration for frontend
management:
  endpoints:
    web:
      exposure:
        include: health,info